# IRSA for multitenant-chatbot | Account: 026544696831 | Region: eu-north-1
apiVersion: v1
kind: ServiceAccount
metadata:
  name: request-router-sa
  namespace: multi-tenant-chatbot
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::026544696831:role/multitenant-chatbot-request-router-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: orchestrator-sa
  namespace: multi-tenant-chatbot
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::026544696831:role/multitenant-chatbot-orchestrator-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vllm-sa
  namespace: multi-tenant-chatbot
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::026544696831:role/multitenant-chatbot-vllm-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rag-sa
  namespace: multi-tenant-chatbot
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::026544696831:role/multitenant-chatbot-rag-role
